#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

echo
echo "Welcome to Linux running on Wasm!"
if [ -x /bin/qjs ]; then
echo "  QuickJS is available: qjs"
fi
echo "Known bugs:"
echo "   * Terminal input freezes after a while (timer issue)."
echo "   * longjmp() does not work (not implemented yet)."
echo

exec /sbin/init -s
